<?php // MyPlugin - Admin Menu



// disable direct file access
if (!defined('ABSPATH')) {
	exit;
}

// add setting menu item to wordpress admin dashboard
acf_add_options_page(array(
	'page_title' => 'تنظیمات سیتی نت',
	'menu_title' => 'تنظیمات سیتی نت',
	'menu_slug'  => 'citynet-settings',
	'capability' => 'can_manage_citynet_settings',
	'redirect'   => false
));

//add panel acf fields
if (function_exists('acf_add_local_field_group')) :

	acf_add_local_field_group(array(
		'key' => 'group_5ae45c1793d11',
		'title' => 'تنظیمات افزونه سیتی نت',
		'fields' => array(
			array(
				'key' => 'field_5ae45f3ff9267',
				'label' => 'سرویس های فعال در صفحه اصلی',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'left',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62f8c09236784',
				'label' => 'سرویس ها',
				'name' => 'cn_services',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 8,
				'max' => 8,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_62f8c0cc36785',
						'label' => 'انتخاب سرویس',
						'name' => 'cn-select-service',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '20',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'readonly' => '1',
					),
					array(
						'key' => 'field_63d11a22c8d2d',
						'label' => 'عنوان سرویس',
						'name' => 'name',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '35',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62f8c2ec36786',
						'label' => 'فعال',
						'name' => 'active',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'placeholder' => '',
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_62f8c32b36787',
						'label' => 'نمایش',
						'name' => 'show',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '15',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'placeholder' => '',
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
					array(
						'key' => 'field_647f14e92d813',
						'label' => 'عدم نمایش لوگو در فوتر',
						'name' => 'hide-logo-footer',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '15',
							'class' => '',
							'id' => ''
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => ''
					)
				),
			),
			array(
				'key' => 'field_6182333330f5e',
				'label' => 'تب‌های اختیاری',
				'name' => 'cn_optional_tabs',
				'type' => 'repeater',
				'instructions' => '<a target="_blank" href="/wp-content/plugins/citynet/assets/other/fonticons/demo.html">راهنمای انتخاب آیکون</a>',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_6182336b1eaf6',
						'label' => 'عنوان',
						'name' => 'cn_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_61877add21ab4',
						'label' => 'لینک',
						'name' => 'cn_url',
						'type' => 'url',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6182342a5b6d7',
						'label' => 'آیکون',
						'name' => 'cn_icon',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '33',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_63ff31c4709f0',
				'label' => 'درج متن های نتایج',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_63ff2d88709ef',
				'label' => 'نمایش متن پروازی یافت نشد',
				'name' => 'not-found-result-flight',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff34bccb94c',
				'label' => 'نمایش متن هتلی یافت نشد',
				'name' => 'not-found-result-hotel',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff3572cb94d',
				'label' => 'نمایش متن پرواز + هنل یافت نشد',
				'name' => 'not-found-result-flightplushotel',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff5220be710',
				'label' => 'نمایش متن تور یافت نشد',
				'name' => 'not-found-result-tour',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff52aebe711',
				'label' => 'نمایش متن پکیج سفر یافت نشد',
				'name' => 'not-found-result-package',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff35b0cb94e',
				'label' => 'نمایش متن تشریفات فرودگاه یافت نشد',
				'name' => 'not-found-result-cip',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_63ff363ccb94f',
				'label' => 'نمایش متن بیمه مسافرتی یافت نشد',
				'name' => 'not-found-result-insurance',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5dde39ab9fb66',
				'label' => 'مسیرهای پروازی جهت سئو',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5dde39bf9fb67',
				'label' => 'مسیر',
				'name' => 'cn_flight-route',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5dde3a9b9fb68',
						'label' => 'مبدا',
						'name' => 'cn_origin',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 35,
							'class' => 'cn-origin',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5dde3aae9fb69',
						'label' => 'مقصد',
						'name' => 'cn_destination',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 35,
							'class' => 'cn-destination',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62a82796c5244',
						'label' => 'نمایش نتایج در صفحه فرود؟',
						'name' => 'cn_search',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 30,
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					)
				),
			),
			array(
				'key' => 'field_625578133b6f6',
				'label' => 'شهرهای هتل جهت سئو',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_625576c33b6f5',
				'label' => '',
				'name' => 'cn_hotel-city',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_6255786c3b6f7',
						'label' => 'برگه',
						'name' => 'cn_citypage',
						'type' => 'page_link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'url',
						'post_type' => 'page',
						'taxonomy' => '',
						'allow_null' => 0,
						'allow_archives' => 1,
						'multiple' => 0,
					),
					array(
						'key' => 'field_62557a303b6f8',
						'label' => 'شهر',
						'name' => 'cn_city',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => 'cn-custom-select',
						),
					),
					array(
						'key' => 'field_62b80f301c001',
						'label' => 'نمایش نتایج در صفحه فرود؟',
						'name' => 'cn_search2',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 1,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					),
				),
			),
			array(
				'key' => 'field_62764b1ff10e8',
				'label' => 'صفحات داخلی هتل جهت سئو',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_62764b4ba3aee',
				'label' => '',
				'name' => 'cn_hotel-page',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_627669912ea7f',
						'label' => 'برگه',
						'name' => 'cn_hotelpage',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'post',
							1 => 'page',
							2 => 'continent',
							3 => 'country',
							4 => 'city',
							5 => 'tour',
							6 => 'state',
							7 => 'location',
						),
						'return_format' => 'id',
						'ui' => 1,
						'taxonomy' => '',
						'allow_null' => 0,
						'allow_archives' => 1,
						'multiple' => 0,
					),
					array(
						'key' => 'field_62764c24bc325',
						'label' => 'هتل',
						'name' => 'cn_hotelname',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '40',
							'class' => '',
							'id' => 'cn-custom-select',
						),
					),
					array(
						'key' => 'field_6406f97731756',
						'label' => 'نمایش پنل سرچ',
						'name' => 'cn_display_panel',
						'type' => 'true_false',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => 20,
							'class' => '',
							'id' => '',
						),
						'message' => '',
						'default_value' => 0,
						'ui' => 1,
						'ui_on_text' => '',
						'ui_off_text' => '',
					)
				),
			),
			array(
				'key' => 'field_62f8c05536783',
				'label' => 'نمایش پنل در صفحات',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_631c98acb68b1',
				'label' => 'نمایش پنل در صفحات',
				'name' => 'cn_panel_pages',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_631c98dfb68b2',
						'label' => 'انتخاب صفحات',
						'name' => 'cn_panel_page',
						'type' => 'post_object',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
							0 => 'post',
							1 => 'page',
						),
						'return_format' => 'id',
						'ui' => 1,
						'taxonomy' => '',
						'allow_null' => 0,
						'allow_archives' => 1,
						'multiple' => 0,
					),
					array(
						'key' => 'field_63200f179df42',
						'label' => 'انتخاب پنل جستجو',
						'name' => 'cn_select_tab',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'instructions' => 'درصورتی تب مورد نظر را انتخاب نکنید تمام سرویس های فعال پنل نمایش داده می شود.',
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'choices' => array(
							"Flight" => "پرواز",
							"Hotel" => "هتل",
							"FlightAndHotel" => "هتل + پرواز",
							"Tour" => "تور",
							"Package" => "پکیج سفر",
							"Cip" => "تشریفات فرودگاهی",
							"Insurance" => "بیمه",
						),
						"multiple" => 1,
						'allow_null' => 0,
						'ui' => 1,
						'other_choice' => 0,
						'default_value' => '',
						'layout' => 'vertical',
						'return_format' => 'value',
						'save_other_choice' => 0,
					),
				),
			),
			array(
				'key' => 'field_626680c83ae40',
				'label' => 'تنظیمات سرچ پرواز',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6267d84c05bce',
				'label' => 'نحوه نمایش شهرها و فرودگاه‌های پرتردد',
				'name' => 'cn-most-visited-airports-columns',
				'type' => 'radio',
				'instructions' => 'مدل ۴ ستون : ۵ سطر اول در ستون اول، ۵ سطر دوم در ستون دوم و به همین ترتیب قرار میگیرند. <br>
				مدل ۲ ستون : ۱۰ سطر  اول در ستون اول و ۱۰ سطر دوم در ستون دوم قرار میگیرند.  <br>
				<br>
				جهت تغییر در ترتیب نمایش، هر سطر را بوسیله drag & drop شماره‌ی آن جابجا کنید.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					2 => ' ۲ ستون',
					4 => '۴ ستون',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 4,
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_6367635c51a55',
				'label' => 'شهر پیش فرض',
				'name' => 'cn_airport_flight',
				'type' => 'text',
				'instructions' => 'محدودیت جستجو پرواز',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => 'cn-custom-select',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62667eec3ae3e',
				'label' => 'شهرها و فرودگاه‌های پرتردد برای پرواز',
				'name' => 'cn-most-visited-airports',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 20,
				'max' => 20,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_62669602ae392',
						'label' => 'عنوان',
						'name' => 'cn-title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_62667fc33ae3f',
						'label' => 'شهر یا فرودگاه',
						'name' => 'cn-airport',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => 'cn-custom-select',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_6268f514be0d9',
				'label' => 'تنظیمات سرچ هتل',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6268f5220c37f',
				'label' => 'نحوه نمایش شهرهای پرتردد',
				'name' => 'cn-most-visited-cities-columns',
				'type' => 'radio',
				'instructions' => 'مدل ۴ ستون : ۵ سطر اول در ستون اول، ۵ سطر دوم در ستون دوم و به همین ترتیب قرار میگیرند. <br>
				مدل ۲ ستون : ۱۰ سطر  اول در ستون اول و ۱۰ سطر دوم در ستون دوم قرار میگیرند.  <br>
				<br>
				جهت تغییر در ترتیب نمایش، هر سطر را بوسیله drag & drop شماره‌ی آن جابجا کنید.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					2 => ' ۲ ستون',
					4 => '۴ ستون',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 4,
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_636a55554760f',
				'label' => 'هتل پیش فرض',
				'name' => 'cn_default_hotel',
				'type' => 'text',
				'instructions' => 'محدودیت جستجو هتل',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => 'cn-custom-select',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6268f55b1d1f5',
				'label' => 'شهرهای پرتردد برای هتل',
				'name' => 'cn-most-visited-cities',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 20,
				'max' => 20,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_6268f566bd07b',
						'label' => 'عنوان',
						'name' => 'cn-title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_6268f5740d655',
						'label' => 'شهر یا فرودگاه',
						'name' => 'cn-city',
						'type' => 'text',
						'instructions' => '',
						'required' => 1,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => 'cn-custom-select',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
			array(
				'key' => 'field_5e6ca09961a38',
				'label' => 'تنظیمات فیلترها',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6264ef183f395',
				'label' => 'مرتب سازی پیش فرض هتل‌ها',
				'name' => 'cn-hotels-sortkey',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'asc' => 'ارزان‌ترین',
					'desc' => 'گران‌ترین',
					'rating' => 'درجه هتل',
					'default' => 'پیش‌فرض',
				),
				'default_value' => 'default',
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'value',
				'placeholder' => '',
			),
			array(
				'key' => 'field_638c8ea5de171',
				'label' => 'تنظیمات سرچ بیمه مسافرتی',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_638c9056f91d4',
				'label' => 'کشورهای پرتردد برای بیمه مسافرتی',
				'name' => 'cn-most-visited-countries',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => array(),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_638f342a1e442',
						'label' => 'عنوان',
						'name' => 'cn-title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_638f341e1e441',
						'label' => 'کشور',
						'name' => 'cn-country',
						'type' => 'select',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '25',
							'class' => '',
							'id' => '',
						),
						'choices' => array(),
						'default_value' => array(),
						'allow_null' => 1,
						'multiple' => 0,
						'ui' => 1,
						'ajax' => 0,
						'return_format' => 'array',
						'placeholder' => '',
					),
				),
			),
			array(
				'key' => 'field_6210daebbd930',
				'label' => 'تنظیمات سرچ تشریفات فرودگاهی',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_636bff0c8184a',
				'label' => 'فرودگاه پیش فرض',
				'name' => 'cn_default_cip',
				'type' => 'text',
				'instructions' => 'مثال IKA',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
			),
			
			array(
				'key' => 'field_647f3c7c36f2b',
				'label' => 'ورود اختیاری ش گذرنامه',
				'name' => 'cn-cip-optional-passport',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_64a4058f1e9ff',
				'label' => 'تنظیمات شیوه پرداخت',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64a406931ea01',
				'label' => 'عدم نمایش کیف پول هنگامی که موجودی صفر است',
				'name' => 'cn-hide-wallet',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_64a4071a1ea02',
				'label' => 'عدم نمایش اعتبار هنگامی که موجودی صفر است',
				'name' => 'cn-hide-credit',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_64a407951ea03',
				'label' => 'عدم نمایش درگاه هنگامی که درگاه فعالی وجود ندارد',
				'name' => 'cn-hide-bank',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_64d9c842b8361',
				'label' => 'تنظیمات ایرلاین',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_64d9c9a1fdacc',
				'label' => 'نمایش فیلتر تامین کنندگان به عنوان اولین فیلتر',
				'name' => 'cn-filter-subsystems',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			
			/* 
			array(
				'key' => 'field_6284eabaec518',
				'label' => 'تنظیمات لودینگ',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6284ead8ec519',
				'label' => 'تصویر لودینگ پرواز',
				'name' => 'cn-flight-loading-img',
				'type' => 'image',
				'instructions' => 'سایز تصویر : 480x170',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '35',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'small',
				'library' => 'all',
				'min_width' => 480,
				'min_height' => 190,
				'min_size' => '',
				'max_width' => 480,
				'max_height' => 190,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6284ee7a6eea5',
				'label' => 'متن لودینگ پرواز',
				'name' => 'cn-flight-loading-text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '65',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'field_6284eb23ec51a',
				'label' => 'تصویر لودینگ هتل',
				'name' => 'cn-hotel-loading-img',
				'type' => 'image',
				'instructions' => 'سایز تصویر : 480x170',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '35',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 480,
				'min_height' => 190,
				'min_size' => '',
				'max_width' => 480,
				'max_height' => 190,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6284eeefc8ec7',
				'label' => 'متن لودینگ هتل',
				'name' => 'cn-hotel-loading-text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '65',
					'class' => '',
					'id' => '',
				),
			),
			array(
				'key' => 'field_6284eb34ec51b',
				'label' => 'تصویر لودینگ پرواز+هتل',
				'name' => 'cn-fph-loading-img',
				'type' => 'image',
				'instructions' => 'سایز تصویر : 480x170',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '35',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 480,
				'min_height' => 190,
				'min_size' => '',
				'max_width' => 480,
				'max_height' => 190,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_6284ef04e214b',
				'label' => 'متن لودینگ پرواز+هتل',
				'name' => 'cn-fph-loading-text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '65',
					'class' => '',
					'id' => '',
				),
			), */

			array(
				'key' => 'field_6374e632b0a82',
				'label' => 'تنظیمات ورود / ثبت‌نام',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_6374e657b0a83',
				'label' => 'عنوان دلخواه به جای شناسه (نام کاربری)',
				'name' => 'cn-auth-username-title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_646871b4664cc',
				'label' => 'ورود رمز یکبار مصرف هنگام افزودن خریدار جدید در ثبت قرارداد',
				'name' => 'cn-auth-automaiton-otp',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				// 'ui_on_text' => 'روشن',
				// 'ui_off_text' => 'تیره',
			),
			array(
				'key' => 'field_6374e695b0a84',
				'label' => 'متن دلخواه برای زیر عنوان',
				'name' => 'cn-auth-subtitle',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => 'شماره موبایل، ایمیل یا نام کاربری خود را وارد نمائید...',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),

			array(
				'key' => 'field_621a240f1fee3',
				'label' => 'روش‌ پیش فرض ورود / ثبت‌ نام',
				'name' => 'cn_login_type',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'mobile' => 'موبایل',
					'email' => 'ایمیل',
					'id' => 'شناسه کاربری',
				),
				'default_value' => array(
					'mobile'
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_622daf8857fa3',
				'label' => 'عدم نمایش روش‌های ورود / ثبت‌ نام :',
				'name' => 'cn_login_hide_show',
				'type' => 'checkbox',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'mobile' => 'موبایل',
					'email' => 'ایمیل',
					'id' => 'شناسه کاربری',
				),
				'allow_custom' => 0,
				'default_value' => false,
				'layout' => 'horizontal',
				'toggle' => 0,
				'return_format' => 'value',
				'save_custom' => 0,
			),
			array(
				'key' => 'field_637b16a173e2d',
				'label' => 'پیش شماره پیش فرض',
				'name' => 'cn_default_mobile_code',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'choices' => array(),
				'default_value' => array(),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_6210e42e2d341',
				'label' => 'پیش شماره ها',
				'name' => 'cn_mobile_codes',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '75',
					'class' => '',
					'id' => '',
				),
				'choices' => array(),
				'default_value' => array(),
				'allow_null' => 1,
				'multiple' => 1,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			array(
				'key' => 'field_6562fb8638fa0',
				'label' => 'عدم نمایش Alert  در تب ثبت‌نام همکار',
				'name' => 'cn-show-alert-register',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_6291c01b57262',
				'label' => 'متن دلخواه برای نمایش در تب ثبت‌نام همکار',
				'name' => 'cn-optional-b2b-signup-txt',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_630b42940be96',
				'label' => 'متن دلخواه برای نمایش در تب مشخصات همکار',
				'name' => 'cn-optional-b2b-signup-txt-2',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'tabs' => 'text',
				'media_upload' => 0,
				'toolbar' => 'full',
				'delay' => 0,
			),
			array(
				'key' => 'field_5dc9070f91bf7',
				'label' => 'تنظیمات دیداری پنل',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60bf24a0eba95',
				'label' => 'کد زبان اصلی سایت',
				'name' => 'cn_site_lang',
				'type' => 'text',
				'instructions' => 'hreflang',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => 'fa',
			),
			array(
				'key' => 'field_62b8282ef219f',
				'label' => 'نوع پیش‌فرض نمایش تقویم',
				'name' => 'cn_datepicker_locale',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'jalali' => 'شمسی',
					'greg' => 'میلادی',
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e396e27abd02',
				'label' => 'لوگو',
				'name' => 'cn_logo',
				'type' => 'image',
				'instructions' => '133x66 png',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '30',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '133',
				'min_height' => '66',
				'min_size' => '',
				'max_width' => '133',
				'max_height' => '66',
				'max_size' => '',
				'mime_types' => 'png',
			),
			array(
				'key' => 'field_64f72f7057124',
				'label' => 'تصویر فوتر در بلیت',
				'name' => 'cn_footer',
				'type' => 'image',
				'instructions' => '700x92 png',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '700',
				'min_height' => '92',
				'min_size' => '',
				'max_width' => '700',
				'max_height' => '92',
				'max_size' => '',
				'mime_types' => 'png',
			),
			array(
				'key' => 'field_62d3dca52782b',
				'label' => 'نمایش دکمه پیگیری خرید؟',
				'name' => 'cn_show_track_order_btn',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_615af80ab1787',
				'label' => 'پیگیری خرید تور',
				'name' => 'cn_tour_track_order',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 33,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'فعال',
				'ui_off_text' => 'غیر فعال',
			),
			array(
				'key' => 'field_61ed06cec30b8',
				'label' => ' عدم نمایش قیمت خط خورده برای پروازهای چارتری؟',
				'name' => 'cn_hide_charter_prices',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 33,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'فعال',
				'ui_off_text' => 'غیر فعال',
			),
			array(
				'key' => 'field_64eb53dce9743',
				'label' => 'عدم نمایش قیمت خط خورده برای پروازهای سیستمی؟',
				'name' => 'cn_hide_system_prices',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 33,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'فعال',
				'ui_off_text' => 'غیر فعال',
			),
			array(
				'key' => 'field_5dc9079d91bf8',
				'label' => 'رنگ اول سایت',
				'name' => 'cn_main-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#004b8f',
			),
			array(
				'key' => 'field_5de2207b0612f',
				'label' => 'رنگ دکمه‌ها',
				'name' => 'cn_buttons-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#01c567',
			),
			array(
				'key' => 'field_609fbf9787ddd',
				'label' => 'رنگ اول darkmode سایت',
				'name' => 'cn_main-darkmode-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#004b8f',
			),
			array(
				'key' => 'field_609fbe7893133',
				'label' => 'رنگ darkmode دکمه‌ها',
				'name' => 'cn_buttons-darkmode-color',
				'type' => 'color_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '25',
					'class' => '',
					'id' => '',
				),
				'default_value' => '#01c567',
			),
			array(
				'key' => 'field_622892062f462',
				'label' => 'تم منو',
				'name' => 'cn_menu-theme',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'روشن',
				'ui_off_text' => 'تیره',
			),
			array(
				'key' => 'field_5ee49fc42a34e',
				'label' => 'تم ویجت',
				'name' => 'cn_widget_theme',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'پیش فرض',
					'theme1' => 'طرح شماره 1',
					'theme2' => 'طرح شماره 2',
					'theme3' => 'طرح شماره 3',
					'theme4' => 'طرح شماره 4',
				),
				'default_value' => array(
					0 => 'default',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_5ece4797eaf5e',
				'label' => 'ادغام منوی وردپرس با منوی پنل؟',
				'name' => 'cn_add-to-wp-menu',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'فعال',
				'ui_off_text' => 'غیر فعال',
			),
			array(
				'key' => 'field_5ff1b84ed08ce',
				'label' => 'شناسه المان',
				'name' => 'cn_custom-panel-menu-wrapper-id',
				'type' => 'text',
				'instructions' => 'id المان html که دکمه‌های ورود/ثبت نام را در منوی وردپرس ادغام می‌کند',
				'required' => 1,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ece4797eaf5e',
							'operator' => '==',
							'value' => 1
						),
					),
				),
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_62f2143db9ba2',
				'label' => 'نحوه نمایش منو',
				'name' => 'cn-menu-show-type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'default' => 'پیش فرض',
					'up' => 'بالای منو',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'default',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_6354fb44b85db',
				'label' => 'عدم نمایش منوی شارژ کیف پول؟',
				'name' => 'cn-hide-charge-credit-menu',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_63d51c43bb57f',
				'label' => 'عدم نمایش منوی ویرایش مشخصات برای کاربر عمومی؟',
				'name' => 'cn-hide-edit-profile-menu',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_62a5e6c3755dc',
				'label' => 'b2c نحوه نمایش نتایج پرواز برای ',
				'name' => 'cn-flights-show-type-b2c',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'simple' => 'ساده',
					'advanced' => 'پیشرفته',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_632978c53b24d',
				'label' => 'b2b نحوه نمایش نتایج پرواز',
				'name' => 'cn-flights-show-type-b2b',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'simple' => 'ساده',
					'advanced' => 'پیشرفته',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_632979363b24e',
				'label' => 'نحوه نمایش نتایج پرواز برای ادمین',
				'name' => 'cn-flights-show-type-admin',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'simple' => 'ساده',
					'advanced' => 'پیشرفته',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_632979393b24f',
				'label' => 'نحوه نمایش نتایج پرواز برای کانتر',
				'name' => 'cn-flights-show-type-counter',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'simple' => 'ساده',
					'advanced' => 'پیشرفته',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => '',
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_64897c5d34189',
                'label' => 'نحوه نمایش تاریخ ثبت',
                'name' => 'display-registration-date',
                'type' => 'radio',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper'=> array(
                    'width' => 50,
                    'class' => '',
                    'id' => ''
				),
                'choices' => array (
                    'jalali' => 'شمسی',
                    'miladi'  => 'میلادی',
                    'both' => 'هردو'
				),
                'allow_null' => 0,
                'other_choice' => 0,
                'default_value' => 'both',
                'layout' => 'horizontal',
                'return_format' => 'value',
                'save_other_choice' => 0
			),
			array(
				'key' => 'field_6328094d3eca7',
				'label' => 'کلاس کابین در سرچ پرواز',
				'name' => 'cn_class_cabin_in_flight',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'Economy' => 'اکونومی',
					'Business' => 'بیزینس',
					'Premium' => 'پریمیوم',
					'First' => 'فرست',
					'All' => '‌همه‌ی کلاس‌ها',
				),
				'default_value' => array(
					0 => 'default',
				),
				'allow_null' => 0,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_62b691926d52c',
				'label' => 'عدم نمایش عنوان چارتری/سیستمی در نتایج پرواز؟',
				'name' => 'cn_hide_flight_type_label',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => 'بله',
				'ui_off_text' => 'خیر',
			),
			array(
				'key' => 'field_6367b11d75d76',
				'label' => 'گزارش مسافران CIP بر اساس',
				'name' => 'cn-cip-manifest-date-type',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					0 => 'تاریخ ثبت',
					1 => 'تاریخ پرواز',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 0,
				'layout' => 'horizontal',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_6306761a2ced1',
				'label' => 'گزارش قراردادها بر اساس تاریخ سفر؟',
				'name' => 'cn-contracts-by-travel',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_64734f6103114',
                'label' => 'عدم نمایش تامین کننده ها برای کانتر',
                'name' => 'cn-hide-suppliers-counter',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => ''
				),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => ''
			),
			array(
				'key' => 'field_64cf614e2c594',
                'label' => 'عدم نمایش تامین کننده ها برای ادمین',
                'name' => 'cn-hide-suppliers-admin',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => ''
				),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => ''
			),
			array(
				'key' => 'field_648d991f55604',
                'label' => 'عدم نمایش لوگو در گزارش قرارداد',
                'name' => 'hide-logo-contract-report',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '50',
                    'class' => '',
                    'id' => ''
				),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => '',
                'ui_off_text' => ''
			),
			array(
				'key' => 'field_632c4ecc3f701',
				'label' => 'دسترسی ویرایش قیمت در وچر cip?',
				'name' => 'cn-cip-voucher-price-edit',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 1,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_64dcd15fe915b',
				'label' => 'عدم نمایش پروازهای تکمیل ظرفیت',
				'name' => 'cn-hide-close-flight',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_657d8885dc75e',
				'label' => 'نمایش اتباع خارجی',
				'name' => 'cn-show-citizens-checkbox',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_64f438671c511',
				'label' => 'عدم نمایش مبلغ های صفر در پرینت پرواز و هتل',
				'name' => 'cn-hide-zero-price',
				'type' => 'true_false',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'message' => '',
				'default_value' => 0,
				'ui' => 1,
				'ui_on_text' => '',
				'ui_off_text' => '',
			),
			array(
				'key' => 'field_637c71acba08a',
				'label' => 'ملیت پیش فرض',
				'name' => 'cn_default_nationality',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(),
				'default_value' => array(),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 1,
				'ajax' => 0,
				'return_format' => 'array',
				'placeholder' => '',
			),
			// array(
			// 	'key' => 'field_642d2a094b2cb',
			// 	'label' => 'ساختن برگه های پنل',
			// 	'name' => 'cn_create_page',
			// 	'type' => 'true_false',
			// 	'instructions' => '',
			// 	'required' => 0,
			// 	'conditional_logic' => 0,
			// 	'wrapper' => array(
			// 		'width' => 50,
			// 		'class' => '',
			// 		'id' => '',
			// 	),
			// 	'message' => '',
			// 	'default_value' => 0,
			// 	'ui' => 1,
			// 	'ui_on_text' => 'بله',
			// 	'ui_off_text' => 'خیر',
			// ),
			array(
				'key' => 'field_5ae45ec3f9264',
				'label' => 'کد امنیتی گوگل',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ae45ed5f9265',
				'label' => 'آیا از کپچای گوگل استفاده شود؟',
				'name' => 'cn_captcha',
				'type' => 'radio',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'on' => 'فعال',
					'off' => 'غیرفعال',
				),
				'allow_null' => 0,
				'other_choice' => 0,
				'default_value' => 'off',
				'layout' => 'vertical',
				'return_format' => 'value',
				'save_other_choice' => 0,
			),
			array(
				'key' => 'field_5ae45f04f9266',
				'label' => 'Site Key',
				'name' => 'cn_site_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ae45ed5f9265',
							'operator' => '==',
							'value' => 'on'
						),
					),
				),
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_6051e9ca1e31e',
				'label' => 'Secret Key',
				'name' => 'cn_secret_key',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => array(
					array(
						array(
							'field' => 'field_5ae45ed5f9265',
							'operator' => '==',
							'value' => 'on'
						),
					),
				),
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5ae46134f9272',
				'label' => 'اطلاعات آژانس',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_5ff5a4abc2342',
				'label' => 'شناسه آژانس',
				'name' => 'cn_org-id',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_648426468aed9',
				'label' => 'baseurl',
				'name' => 'cn_baseurl',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_618b6cd830068',
				'label' => 'شناسه inventory آژانس',
				'name' => 'cn_org-inventory-id',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => 50,
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_618b70d3cae3a',
				'label' => 'ارز پیش‌ فرض',
				'name' => 'cn_default_currency',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'choices' => array(
					'IRR' => 'ریال',
					'USD' => 'دلار',
					'DHS' => 'درهم',
					'EUR' => 'یورو',
					'TRY' => 'لیر ترکیه',
					'RUB' => 'روبل'
				),
				'allow_null' => 1,
				'multiple' => 0,
				'ui' => 0,
				'return_format' => 'value',
				'ajax' => 0,
				'placeholder' => '',
			),
			array(
				'key' => 'field_604de72b63a1b',
				'label' => 'شماره تماس آژانس',
				'name' => 'cn_agency_phone_number',
				'type' => 'number',
				'instructions' => ' در تب های غیر فعال و صفحه پشتیبانی pwa نمایش داده می شود',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5e4ba152dcd44',
				'label' => 'تنظیمات PWA',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_60a0b082cded4',
				'label' => 'بنر منو',
				'name' => 'cn_menu_banner',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_63621ad7f9478',
				'label' => 'متن تماس با ما',
				'name' => 'cn_agency_phone_txt',
				'type' => 'text',
				'instructions' => 'این فیلد در قسمت پشتیبانی پایین شماره تلفن نمایش داده می شود',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_60a0a4f5d1f49',
				'label' => 'تصویر بنر اول',
				'name' => 'cn_pwa_banner1',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array(
				'key' => 'field_60a0aa7d4058c',
				'label' => 'لینک بنر اول',
				'name' => 'cn_pwa_banner_link1',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_60a0ad4eae1f5',
				'label' => 'تصویر بنر دوم',
				'name' => 'cn_pwa_banner2',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array(
				'key' => 'field_60a0ad5ff231b',
				'label' => 'لینک بنر دوم',
				'name' => 'cn_pwa_banner_link2',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '50',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba189dcd45',
				'label' => 'آدرس اینستاگرام',
				'name' => 'cn_instagram',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba1b3dcd46',
				'label' => 'آدرس فیس بوک',
				'name' => 'cn_facebook',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba1c8dcd47',
				'label' => 'آدرس توییتر',
				'name' => 'cn_twitter',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba1d7dcd48',
				'label' => 'آدرس واتس اپ',
				'name' => 'cn_whatsapp',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba1e8dcd49',
				'label' => 'آدرس تلگرام',
				'name' => 'cn_telegram',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5e4ba1f9dcd4a',
				'label' => 'آدرس لینکدین',
				'name' => 'cn_linkedin',
				'type' => 'url',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '33',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_60a0adef768e7',
				'label' => 'عنوان و لینک‌های منو',
				'name' => 'cn_menu_items',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 5,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_60a0ae10cf9a3',
						'label' => 'عنوان',
						'name' => 'cn_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_60a0ae22e90ff',
						'label' => 'لینک',
						'name' => 'cn_link',
						'type' => 'url',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '50',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'citynet-settings',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
